# Introduction à la programmation avec Python

## À propos du Notebook Jupyter
* Plusieurs opérations telles que l'exécution ou l'insertion d'une cellule peuvent se faire à l'aide de la barre d'outils ci-haut.
* Voici une liste de raccourcis pour le clavier :

| Raccourcis            | Action                                |
|-----------------------|---------------------------------------|
| **Maj + Entrée**      | Exécuter le code                      |
| Double-clic ou Entrée | Entrer dans la boîte (mode édition)   |
| Esc                   | Sordir de la boîte (mode commandes)   |

| En mode édition: |                        |
|------------------|------------------------|
| Tab              | Compléter une commande |

| En mode commandes: |                                |
|--------------------|--------------------------------|
| b                  | Insérer une cellule en-dessous |
| a                  | Insérer une cellule au-dessus  |
| s                  | Sauvegarder                    |
| x/c/v              | Couper/Copier/Coller           |

In [1]:
import numpy

In [2]:
numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [3]:
poids_kg = 55

In [4]:
print(poids_kg)

55


In [5]:
print("Poids en livres: ", 2.2 * poids_kg)

Poids en livres:  121.00000000000001


In [7]:
poids_lb = 2.2 * poids_kg
print("Poids en livres: ", poids_lb)

Poids en livres:  121.00000000000001


In [11]:
poids_kg = 57.5
poids_lb = 2.2 * poids_kg
print(poids_kg)
print(poids_lb)

57.5
126.50000000000001


In [12]:
poids_kg = 100
print(poids_kg)
print(poids_lb)

100
126.50000000000001


In [13]:
donnees = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=',')

In [14]:
print(donnees)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [15]:
print(type(donnees))

<class 'numpy.ndarray'>


In [16]:
print(donnees.shape)

(60, 40)


In [18]:
print("Patient 0, 3e journee: ", donnees[0, 2])

Patient 0, 3e journee:  1.0


In [20]:
print("Patient du milieu: ", donnees[30, 20])

Patient du milieu:  13.0


In [21]:
print(donnees[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [22]:
petit = donnees[:3, 36:]
print(petit)

[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]


In [24]:
doubledonnees = donnees * 2.0

In [26]:
print("Original:")
print(donnees)
print("Double:")
print(doubledonnees)

Original:
[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]
Double:
[[ 0.  0.  2. ...,  6.  0.  0.]
 [ 0.  2.  4. ...,  2.  0.  2.]
 [ 0.  2.  2. ...,  4.  2.  2.]
 ..., 
 [ 0.  2.  2. ...,  2.  2.  2.]
 [ 0.  0.  0. ...,  0.  4.  0.]
 [ 0.  0.  2. ...,  2.  2.  0.]]


In [27]:
tripledonnees = doubledonnees + donnees

In [28]:
print("Triple donnees: ")
print(tripledonnees[:3, 36:])

Triple donnees: 
[[ 6.  9.  0.  0.]
 [ 3.  3.  0.  3.]
 [ 6.  6.  3.  3.]]


In [29]:
doubledonnees * donnees

array([[  0.,   0.,   2., ...,  18.,   0.,   0.],
       [  0.,   2.,   8., ...,   2.,   0.,   2.],
       [  0.,   2.,   2., ...,   8.,   2.,   2.],
       ..., 
       [  0.,   2.,   2., ...,   2.,   2.,   2.],
       [  0.,   0.,   0., ...,   0.,   8.,   0.],
       [  0.,   0.,   2., ...,   2.,   2.,   0.]])

In [30]:
print("Maximum:", donnees.max())
print("Minimum:", donnees.min())
print("Dev. std:", donnees.std())

Maximum: 20.0
Minimum: 0.0
Dev. std: 4.61383319712


In [35]:
patient0 = donnees[0, :]
print(patient0.shape)

(40,)


In [37]:
print("Moyenne patient 0:", patient0.max())

Moyenne patient 0: 18.0


In [38]:
print(donnees.mean(axis=0))

[  0.           0.45         1.11666667   1.75         2.43333333   3.15
   3.8          3.88333333   5.23333333   5.51666667   5.95         5.9
   8.35         7.73333333   8.36666667   9.5          9.58333333
  10.63333333  11.56666667  12.35        13.25        11.96666667
  11.03333333  10.16666667  10.           8.66666667   9.15         7.25
   7.33333333   6.58333333   6.06666667   5.95         5.11666667   3.6
   3.3          3.56666667   2.48333333   1.5          1.13333333
   0.56666667]


In [39]:
donnees.mean(axis=0).shape

(40,)