In [1]:
1+2+3

6

In [2]:
import numpy

In [3]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [4]:
poids_kg = 55


In [5]:
print(poids_kg)

55


In [6]:
print('Poids en kilogrammes:', poids_kg)

Poids en kilogrammes: 55


In [8]:
poids_kg = 57.5
print('Poids en livres:', 2.2 * poids_kg)

Poids en livres: 126.50000000000001


In [9]:
poids_lbs = 2.2*poids_kg
print('Poids en kg:', poids_kg, 'Poids en livres:', poids_lbs)

Poids en kg: 57.5 Poids en livres: 126.50000000000001


In [10]:
print poids_kg,poids_lbs

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-10-2955b2f3353f>, line 1)

In [11]:
3 / 2

1.5

In [12]:
3 // 2

1

In [13]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [14]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [15]:
print(type(data))

<class 'numpy.ndarray'>


In [16]:
print(data.shape)

(60, 40)


In [17]:
print(data[0, 0])

0.0


In [18]:
print(data[1, 2])

2.0


In [19]:
print('Donnee centrale', data[30, 20])

Donnee centrale 13.0


In [20]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


In [21]:
print(data[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [22]:
print(data[:10, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]
 [ 0.  1.  1.  3.  3.  1.  3.  5.  2.  4.]
 [ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [23]:
print(data[5::12, 36:])

[[ 4.  3.  2.  1.]
 [ 3.  0.  1.  0.]
 [ 2.  1.  0.  1.]
 [ 2.  2.  0.  0.]
 [ 2.  2.  2.  1.]]


In [24]:
small = data[5::12, 36:]
doubleSmall = small * 2

In [25]:
print(doubleSmall)

[[ 8.  6.  4.  2.]
 [ 6.  0.  2.  0.]
 [ 4.  2.  0.  2.]
 [ 4.  4.  0.  0.]
 [ 4.  4.  4.  2.]]


In [26]:
data.mean()

6.1487499999999997

In [29]:
data.max()

20.0

In [30]:
data.min()

0.0

In [31]:
data.max(axis=1)

array([ 18.,  18.,  19.,  17.,  17.,  18.,  17.,  20.,  17.,  18.,  18.,
        18.,  17.,  16.,  17.,  18.,  19.,  19.,  17.,  19.,  19.,  16.,
        17.,  15.,  17.,  17.,  18.,  17.,  20.,  17.,  16.,  19.,  15.,
        15.,  19.,  17.,  16.,  17.,  19.,  16.,  18.,  19.,  16.,  19.,
        18.,  16.,  19.,  15.,  16.,  18.,  14.,  20.,  17.,  15.,  17.,
        16.,  17.,  19.,  18.,  18.])

In [32]:
data.mean(axis=0)

array([  0.        ,   0.45      ,   1.11666667,   1.75      ,
         2.43333333,   3.15      ,   3.8       ,   3.88333333,
         5.23333333,   5.51666667,   5.95      ,   5.9       ,
         8.35      ,   7.73333333,   8.36666667,   9.5       ,
         9.58333333,  10.63333333,  11.56666667,  12.35      ,
        13.25      ,  11.96666667,  11.03333333,  10.16666667,
        10.        ,   8.66666667,   9.15      ,   7.25      ,
         7.33333333,   6.58333333,   6.06666667,   5.95      ,
         5.11666667,   3.6       ,   3.3       ,   3.56666667,
         2.48333333,   1.5       ,   1.13333333,   0.56666667])